# Generated by Django 5.1.1 on 2024-09-24 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championships_tennis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('avatar', models.ImageField(upload_to='championships/%Y/%m/%d')),
                ('start_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('flag', models.ImageField(upload_to='flags/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tennis_players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('avatar', models.ImageField(upload_to='players/%Y/%m/%d')),
                ('start_date', models.DateField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Football_club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(default='', upload_to='')),
                ('point', models.ImageField(default=0, upload_to='')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('players_count', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('countries', models.ManyToManyField(to='football.countries')),
                ('games', models.ManyToManyField(to='football.games')),
            ],
        ),
        migrations.CreateModel(
            name='Championships_football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('avatar', models.ImageField(upload_to='championships/%Y/%m/%d')),
                ('start_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('clubs_count', models.IntegerField()),
                ('countries', models.ManyToManyField(to='football.countries')),
                ('clubs', models.ManyToManyField(to='football.football_club')),
            ],
        ),
        migrations.CreateModel(
            name='Fovorite_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.games')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='football.countries')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('content', models.TextField()),
                ('country', models.ManyToManyField(to='football.countries')),
                ('games', models.ManyToManyField(to='football.games')),
            ],
        ),
        migrations.CreateModel(
            name='Players_football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('avatar', models.ImageField(upload_to='players/%Y/%m/%d')),
                ('start_date', models.DateField()),
                ('age', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('football_clubs', models.ManyToManyField(to='football.football_club')),
            ],
        ),
    ]
